name: Build

on:
  push:
    branches: [master]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install SDL2
        run: sudo apt-get install -y libsdl2-dev libsdl2-image-dev
      - name: Compile
        id: compile
        uses: rust-build/rust-build.action@v1.4.3
        with:
          RUSTTARGET: x86_64-unknown-linux-musl
          UPLOAD_MODE: none
          TOOLCHAIN_VERSION: nightly
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Binary
          path: |
            ${{ steps.compile.outputs.BUILT_ARCHIVE }}
            ${{ steps.compile.outputs.BUILT_CHECKSUM }}
