name: Build

on:
  push:
    branches: [master]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install SDL2
        run: |
          sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu `lsb_release -sc` main universe restricted multiverse"
          sudo apt-get update -y -qq
          sudo apt-get install libsdl2-dev libsdl2-image-dev
      - name: Compile
        id: compile
        run: cargo build -r
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Binary
          path: target/release/block_byte
